sonar.projectKey=ScreenScribe
sonar.projectName=ScreenScribe
sonar.sources=src
sonar.exclusions=dist/**,build/**,tesseract_bundle/**,resources/**,logs/**,config/history.json,config/settings.json
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml